name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        vim:
          - v8.2.2000
          - v8.2.1000
          - v8.2.0000
    steps:
      - uses: actions/checkout@v2
      - name: Setup Vim
        uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          version: ${{ matrix.vim }}
      - name: Setup vim-themis
        uses: actions/checkout@v2
        with:
          repository: thinca/vim-themis
          path: vim-themis
      - name: Run tests
        shell: bash -xe {0}
        env:
          THEMIS_VIM: ${{ steps.vim.outputs.executable }}
        run: |
          $THEMIS_VIM --version
          ./vim-themis/bin/themis
