name: Test

on:
  push:
    branches:
      - master
      - vim9
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        neovim:
          - false
        version:
          - nightly
          - v9.1.0000
          - v9.0.2000
          - v9.0.1000
          - v9.0.0000
          - v8.2.5000
          - v8.2.4053
    name: >-
      Test --
      ${{ matrix.neovim && 'Neovim' || 'Vim' }}
      ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Setup Vim
        uses: rhysd/action-setup-vim@v1.3.0
        id: vim
        with:
          neovim: ${{ matrix.neovim }}
          version: ${{ matrix.version }}
      - name: Setup vim-themis
        uses: actions/checkout@v4.1.1
        with:
          repository: thinca/vim-themis
          path: vim-themis
      - name: Run tests
        shell: bash -xe {0}
        env:
          VIM_EXECUTABLE: ${{ steps.vim.outputs.executable }}
        run: |
          export PATH="./vim-themis/bin:$PATH"
          make "test-$(basename "$VIM_EXECUTABLE")"
