name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        name: [vim-v82-latest, vim-v82-0000]
        include:
          - name: vim-v82-latest
            os: ubuntu-latest
            vim_version: 8.2.2576
          - name: vim-v82-0000
            os: ubuntu-latest
            vim_version: 8.2.0
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v1
      - name: Download vim
        shell: bash -xe {0}
        run: |
          mkdir -p ~/vim/bin
          curl -L https://github.com/vim/vim-appimage/releases/download/v${{matrix.vim_version}}/GVim-v${{matrix.vim_version}}.glibc2.15-x86_64.AppImage -o ~/vim/bin/vim
          chmod u+x ~/vim/bin/vim
      - name: Download test runner
        shell: bash -xe {0}
        run: git clone --depth 1 --single-branch https://github.com/thinca/vim-themis ~/themis
      - name: Run tests
        shell: bash -xe {0}
        run: |
          export PATH=~/vim/bin:$PATH
          export PATH=~/themis/bin:$PATH
          export THEMIS_VIM=vim
          vim --version
          themis
