name: Test

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        neovim:
          - false
        version:
          - nightly
          - v8.2.2290
          - v8.2.2280
          - v8.2.2270
          - v8.2.2260
          - v8.2.2250
          - v8.2.2240
          - v8.2.2230
          - v8.2.2220
          - v8.2.2210
    steps:
      - uses: actions/checkout@v2
      - name: Setup Vim
        uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: ${{ matrix.neovim }}
          version: ${{ matrix.version }}
      - name: Setup vim-themis
        uses: actions/checkout@v2
        with:
          repository: thinca/vim-themis
          path: vim-themis
      - name: Run tests
        shell: bash -xe {0}
        env:
          VIM_EXECUTABLE: ${{ steps.vim.outputs.executable }}
        run: |
          export PATH="./vim-themis/bin:$PATH"
          make "test-$(basename "$VIM_EXECUTABLE")"
